# Generated by Django 5.1.4 on 2025-01-19 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='fb',
        ),
    ]
