# Generated by Django 5.1.4 on 2025-02-04 14:24

from django.db import migrations, models
from django.conf import settings

def set_default_user(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Member = apps.get_model('team', 'member')
    default_user = User.objects.first()  # Assuming the first user as default
    for member in Member.objects.all():
        member.user = default_user
        member.save()

class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_member_position_member_user_member_year'),
    ]

    operations = [
        migrations.RunPython(set_default_user),
    ]