# Generated by Django 5.1.4 on 2025-02-05 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_alter_member_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='position',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.RemoveField(
            model_name='member',
            name='year',
        ),
    ]
