# Generated by Django 5.1.4 on 2025-02-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_rename_twitter_member_instagram_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
