# Generated by Django 5.1.4 on 2025-02-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_alter_member_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='position',
            field=models.IntegerField(null=True),
        ),
    ]
