# Generated by Django 5.1.4 on 2025-07-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0012_alter_member_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='year',
            field=models.CharField(default='2024', max_length=10, null=True),
        ),
    ]
