# Generated by Django 5.1.4 on 2025-08-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0013_member_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamDisplaySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_2025_members', models.BooleanField(default=True)),
            ],
        ),
    ]
