# Generated by Django 5.1.4 on 2025-02-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
