# Generated by Django 5.1.4 on 2025-07-31 13:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.CharField(help_text='e.g., 2024-25', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('drive_link', models.URLField(help_text='Google Drive link to the magazine')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='magazine_covers/')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('download_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
