# Generated by Django 5.1.4 on 2025-07-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Upload the magazine PDF', null=True, upload_to='magazine_pdfs/'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='drive_link',
            field=models.URLField(blank=True, help_text='Google Drive link to the magazine', null=True),
        ),
    ]
