# Generated by Django 5.1.4 on 2025-07-31 15:37

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_magazine_pdf_file_alter_magazine_drive_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='magazine_covers/'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Upload the magazine PDF', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='magazine_pdfs/'),
        ),
    ]
